# railway.toml

[project]
name = "SocialAppFrontend"  # Replace with your project name

[[services]]
name = "SocialAppFrontend"
path = "./user"  # The path to your React app

[build]
builder = "nixpacks"  # Use Nixpacks to auto-detect the build environment

[deploy]
context = "./user"  # Set deployment context to the user directory

[env]
NODE_ENV = "production"  # Add any necessary environment variables here
